### ISSUE TITLE
doesn't work when using `patch: true`

### ISSUE THREAD

**Issue by jamesdixon** [bsiddiqui/bookshelf-bcrypt#10]
Hi there - I just ran into an issue where my password was not being hashed and instead saved in clear text. I tracked the issue down to `patch: true` being set in the options. 

For reference, I use your wonderful `bookshelf-modelbase` plugin as well. Through that, I was calling:

`model.update(...)`

which resulted in the password not being hashed.

I'm not sure if this is a plugin issue or an underlying Bookshelf issue, but wanted to report it.

Thanks!

**Comment by bsiddiqui** [comment]
@jamesdixon to clarify you were using Model.update(data) and the data was not being encrypted?

This is probably a probnlem with `bookshelf-bcrypt` since it should handle `patch: true`. Probably won't have time to look into a solution for a bit but you're more than welcome to make a PR if you find a solution. If not we'll dive into it when we have some time. 

Cheers!
